# -*- coding: utf-8 -*-
"""university_admission_bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bq73PjcjSy9uZuD7BrrWPKluJ6kQkQ86
"""

!pip install -q transformers sentencepiece torch

from transformers import pipeline

llm = pipeline(
    task="text2text-generation",
    model="google/flan-t5-small",
    device=-1,        # force CPU (avoids GPU/CUDA errors)
    max_length=150
)

def llm_response(prompt):
    response = llm(prompt)[0]["generated_text"]
    return response

def load_university_data():
    return {
        "university_name": "JAI University",
        "engineering_courses": {
            "B.Tech Computer Science": 120000,
            "B.Tech Artificial Intelligence": 130000,
            "B.Tech Data Science": 125000,
            "B.Tech Cyber Security": 128000,
            "B.Tech Electronics": 110000,
            "B.Tech Mechanical": 105000,
            "B.Tech Civil": 100000
        },
        "hostel_fees": {
            "non-ac": {
                "4-sharing": 95000,
                "3-sharing": 100000,
                "2-sharing": 105000,
                "single-sharing": 110000
            },
            "ac": {
                "4-sharing": 110000,
                "3-sharing": 115000,
                "2-sharing": 120000,
                "single-sharing": 125000
            }
        },
        "base_admission_fee": 3000,
        "admin_contacts": {
            "Admission Office": "9876543210",
            "Student Help Desk": "9123456780",
            "Email": "admissions@jaiuniversity.edu"
        }
    }

def calculate_admission_fee(percentage, base_fee):
    return 0 if percentage >= 80 else base_fee

def select_hostel(hostel_data):
    hostel_type = input("Choose hostel type (AC / Non-AC): ").lower()
    if hostel_type not in hostel_data:
        hostel_type = "non-ac"

    print("\nAvailable Sharing Options:")
    for s, f in hostel_data[hostel_type].items():
        print(f"• {s} : ₹{f}")

    sharing = input("Choose sharing type: ").lower()
    if sharing not in hostel_data[hostel_type]:
        sharing = "4-sharing"

    return hostel_type.upper(), sharing, hostel_data[hostel_type][sharing]

def get_student_details():
    print("\n--- Student Details ---")
    name = input("Student Name: ")
    dob = input("Date of Birth (DD-MM-YYYY): ")
    percentage = float(input("12th Percentage: "))
    return name, dob, percentage

def generate_bill(course, course_fee, hostel_fee, admission_fee):
    total = course_fee + hostel_fee + admission_fee

    print("\n========== ADMISSION BILL ==========")
    print(f"Course Fee    : ₹{course_fee}")
    print(f"Hostel Fee    : ₹{hostel_fee}")
    print(f"Admission Fee : ₹{admission_fee}")
    print("-----------------------------------")
    print(f"TOTAL         : ₹{total}")
    print("===================================")

def slot_booking_receipt(name, course):
    print("\n🎉 ADMISSION CONFIRMED 🎉")
    print("------ SLOT BOOKING RECEIPT ------")
    print(f"Student Name : {name}")
    print(f"Course       : {course}")
    print("Slot Status  : BOOKED")
    print("Reporting To : Admission Office")
    print("---------------------------------")

def chatbot():
    data = load_university_data()

    intro = f"Welcome to {data['university_name']}. You are an admission assistant chatbot."
    print(llm_response(intro))

    print("\nEngineering Courses Available:")
    for c in data["engineering_courses"]:
        print(f"• {c}")

    course = input("\nSelect a course: ")
    if course not in data["engineering_courses"]:
        print("Invalid course.")
        return

    course_fee = data["engineering_courses"][course]

    hostel_required = input("Do you need hostel? (yes/no): ").lower()
    hostel_fee = 0

    if hostel_required == "yes":
        h_type, sharing, hostel_fee = select_hostel(data["hostel_fees"])
        print(llm_response(f"User selected {h_type} hostel with {sharing}."))

    print("\nAdmission Office Contacts:")
    for d, c in data["admin_contacts"].items():
        print(f"{d}: {c}")

    proceed = input("\nProceed with admission booking? (yes/no): ").lower()
    if proceed != "yes":
        print("Admission cancelled.")
        return

    name, dob, percentage = get_student_details()
    admission_fee = calculate_admission_fee(percentage, data["base_admission_fee"])

    if admission_fee == 0:
        print(llm_response("Congratulate the student for scoring above 80 percent and getting free admission."))
    else:
        print(f"Admission Fee: ₹{admission_fee}")

    generate_bill(course, course_fee, hostel_fee, admission_fee)
    slot_booking_receipt(name, course)

chatbot()

